const abbrMap ={
  'US Total Population':'US Pop',
  'Deaths Per Year':'DPY',
  'Estimated Firearm Owners in USA (based on 30% polls)':'Est Firearm Owners',
  'Firearms Includes Assault + Suicide Data':'Gun+As+Sui',
  'Motor Vehicle Deaths':'MVD',
  'Poison Deaths (All Intents)':'Poi',
  'Poison Deaths (Accidental)':'Poi(A)',
  'Falling Deaths ':'Fall',
  'Alcohol Induced Deaths':'Alch',
  'Drug Induced Deaths':'Drugs',
  'Assault (resulting in death)  Includes Firearm data':'Assault',
  'Intentional Self Harm (Suicide) Includes Firearm data':'Self Harm',
  'Malignant Neoplasms (MN) - Cancers':'MN-Cancers',
  'MN of Trachea, Bronchus, lung':'MN-Tra,Bro,Lung',
  'MN of lymphoid, hematopoietic':'MN-Lymph',
  'MN of Colon':'MN-Colon',
  'MN of Pancreas':'MN-Panc',
  'MN of Breast':'MN-Breast',
  'MN of Other':'MN-Other',
  'Major Cardiovascular Diseases (MC)':'MC',
  'MC of Heart':'MC-Heart',
  'Pneumonia':'Pneum',
  'Chronic Lower Resp':'Chron-Resp',
  'Chronic Liver Disease':'Chron-Liv',
  'Renial Failure (Kidney)':'RF(Kidn)',
  'Diabetes':'Diabetes',
  '\'Alzheimer\'\'s\'':'Alzheimer\'s',
}

module.exports = abbrMap 