const abbrMap ={
  'US Total Population':'US Pop',
  'Deaths Per Year':'DPY',
  'Estimated Firearm Owners in USA (based on 30% polls)':'Est Firearm Owners',
  'Firearms Includes Assault + Suicide Data':'Gun+As+Sui',
  'Motor Vehicle Deaths':'MVD',
  'Poison Deaths (All Intents)':'Poi',
  'Poison Deaths (Accidental)':'Poi(A)',
  'Falling Deaths ':'Fall',
  'Alcohol Induced Deaths':'Alch',
  'Drug Induced Deaths':'Drugs',
  'Assault (resulting in death)  Includes Firearm data':'Assault',
  'Intentional Self Harm (Suicide) Includes Firearm data':'Self Harm',
  'Malignant Neoplasms (MN) - Cancers':'MN-Cancers',
  'MN of Trachea, Bronchus, lung':'MN-Tra,Bro,Lung',
  'MN of lymphoid, hematopoietic':'MN-Lymph',
  'MN of Colon':'MN-Colon',
  'MN of Pancreas':'MN-Panc',
  'MN of Breast':'MN-Breast',
  'MN of Other':'MN-Other',
  'Major Cardiovascular Diseases (MC)':'MC',
  'MC of Heart':'MC-Heart',
  'Pneumonia':'Pneum',
  'Chronic Lower Resp':'Chron-Resp',
  'Chronic Liver Disease':'Chron-Liv',
  'Renial Failure (Kidney)':'RF(Kidn)',
  'Diabetes':'Diabetes',
  '\'Alzheimer\'\'s\'':'Alzheimer\'s',
}

const abbrMapOverview = {
  'US Total Population':'US Pop',
  'Deaths Per Year':'DPY',
  'Death Per Year % vs Population':'DPY v Pop',
  'Firearm Deaths Per Year':'Fr DPY',
  'Firearm Suicide':'Fr Suicide',
  'Firearm Suicide % Vs Firearm Deaths':'Fr.Suicide % Fr Deaths',
  'FirearmSuicide by Firearm Vs Yearly Deaths':'Fr.Suicide vs Yr Deaths',
  'Firearm Assault/Homicide':'Fr. Assault/Homicide',
  'Firearm Assault/Homicide % Vs Firearm Deaths':'Fr. Assault/Homicide% vs Fr Deaths',
  'Assault/Homicide by Firearm Vs Yearly Deaths':'Assault by Fr. vs Yr Deaths',
  'Firearm Other':'Firearm Other',
  'Other % Vs Firearm Deaths':'Other % Vs Fr Deaths',
  'Other Firearm Vs Yearly Deaths':'Other Fr Vs Yr Deaths',
  'Overall Firearm Death % vs population':'Overall Fr. Death % vs pop',
  'Overall Firearm Death % vs Yearly Deaths':'Overall Fr. Death % vs Yr Deaths',
  'Motor Vehicle Deaths':'MV Deaths',
  'Motor Vehicle % vs Population':'MV % vs Pop',
  'Motor Vehicle % vs Yearly Deaths':'MV % vs Yr Deaths',
  'Poison Deaths (All Intents)':'Poison Deaths (All Intents)',
  'Overall Poison Deaths % vs Population':'Overall Poison Deaths % vs Pop',
  'Overall Poison Deaths % vs Yearly Deaths':'Overall Poison Deaths % vs Yr Deaths',
  'Poison Deaths (Accidental)':'Poison Deaths (Accidental)',
  '% vs Poison Deaths':'% vs Poison Deaths',
  '% vs Yearly Deaths':'% vs Yr Deaths',
  'Falling Deaths':'Falling Deaths',
  'Falling Death % vs Population':'Falling Death % vs Pop',
  'Falling Death % vs Yearly Deaths':'Falling Death % vs Yr Deaths',
  'Alcohol Induced Deaths':'Alcohol Induced Deaths',
  'Alcohol Death % vs Population':'Alcohol Death % vs Pop',
  'Alcohol Death % vs Yearly Deaths':'Alcohol Death % vs Yr Deaths',
  'Drug Induced Deaths':'Drug Induced Deaths',
  'Drug Death % vs Population':'Drug Death % vs Pop',
  'Drug Death % vs Yearly Deaths':'Drug Death % vs Yr Deaths',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  
}

module.exports = abbrMap 